### ISSUE TITLE
(1.2) uninitialized constant Flipper::CLI::IRB (NameError)

### ISSUE THREAD

**Issue by manewitz** [flippercloud/flipper#817]
Excited to check out the 1.2 CLI but running into this error around IRB colorization. `flipper --help` runs correctly but list, show, enable and disable are giving the same NameError.
I'm on Ruby 3.2.2. via asdf. Any ideas?

```
❯ flipper list
/Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:213:in `colorize': uninitialized constant Flipper::CLI::IRB (NameError)

      IRB::Color.colorize(text, options)
         ^^^^^^^
Did you mean?  ERB
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:152:in `block in feature_summary'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:149:in `map'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:149:in `feature_summary'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:68:in `block (2 levels) in initialize'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:232:in `run'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:115:in `run'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/lib/flipper/cli.rb:6:in `run'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/flipper-1.2.0/exe/flipper:5:in `<top (required)>'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/bin/flipper:25:in `load'
	from /Users/mikemanewitz/.asdf/installs/ruby/3.2.2/bin/flipper:25:in `<main>'
```

**Comment by aitor** [comment]
The same error here on Ruby 2.7.8 and 3.1.4 via rbenv. Manually requiring `irb` in the cli code in the gem does NOT solve it and moves the error to a point where `IRB::Color::WHITE` is referenced.

**Comment by manewitz** [comment]
here's mine:
```
❯ rails --version
Rails 7.1.2
❯ irb --version
irb 1.11.1 (2024-01-08)
❯ gem --version
3.5.4
```

**Comment by bkeepers** [comment]
Ok, I was finally able to duplicate this in a Rails 7.0 app. Rails 7.1 [added a dependency on the `irb` gem](https://github.com/rails/rails/commit/4fefed42398867e4a103d48267395481b2845cb3), which is [where new development is happening](https://github.com/ruby/irb) to try to get parity with pry.

So we either need to make Flipper depend on `irb` gem as well, or just make colorization optional if `IRB::Color` is defined. The latter would probably be my preference.
