### ISSUE TITLE
Flipper 1.2.2 breaks my CI

### ISSUE THREAD

**Issue by n-rodriguez** [flippercloud/flipper#831]
Hi there!

Due to https://github.com/flippercloud/flipper/blob/main/lib/flipper/test_help.rb (since Flipper 1.2.0), which reset/redefines Flipper config before each spec, my CI is broken with some weird errors that has nothing to do with Flipper, so the debug was kind of hard. But I finally found it :)

It works with Flipper 1.1.2 because this file doesn't exist in this version.

Thank you!

**Comment by jnunemaker** [comment]
The file was added intentionally as the default for tests. We had a few issues at first but we’ve worked through them and everyone seems ok now. Can you describe what the errors were? I’m not sure how to help without background on what happened and what your expectations were. 

I’m closing this to keep things tidy but happy to keep talking and help if there is anything actionable we can do.

**Comment by n-rodriguez** [comment]
> Can you describe what the errors were? I’m not sure how to help without background on what happened and what your expectations were.

Sure, hope this helps :

```sh
nicolas@MacBook-Pro-de-Nicolas:~/PROJECTS/CONCERTO/concerto$ bin/rspec ./spec/concepts/polymorphic/sms_campaigns/operation/create_spec.rb:38
[2024-02-01T04:02:27.176566 #95314 #]  INFO [] - concerto.rake: Validating config
[2024-02-01T04:02:27.288882 #95314 #]  INFO [] - concerto.rake: Starting app ({:env=>"test", :pid=>95314})
[2024-02-01T04:02:27.288935 #95314 #]  INFO [] - concerto.rake: Enabling Ruby warnings
Run options: include {:locations=>{"./spec/concepts/polymorphic/sms_campaigns/operation/create_spec.rb"=>[38]}}

Randomized with seed 47458
F

Failures:

  1) Polymorphic::SmsCampaigns::Operation::Create when user is a Commercial valid creation with valid params is persisted
     Failure/Error: raise ::Pundit::NotAuthorizedError, policy: @policy, record: @record, query: @query

     Pundit::NotAuthorizedError:
       not allowed to  this SmsCampaign
     # ./app/concepts/concerns/base_operation/pundit/error.rb:48:in `call'
     # ./app/concepts/concerns/base_operation/pundit/error.rb:37:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit/task_adapter.rb:32:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit/task_adapter.rb:73:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/call_task.rb:13:in `call_task'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `block in call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `each'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit.rb:45:in `block in call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit.rb:44:in `loop'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit.rb:44:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity.rb:13:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-dsl-linear-1.2.4/lib/trailblazer/activity/dsl/linear/strategy.rb:105:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-operation-0.10.1/lib/trailblazer/operation/public_call.rb:61:in `call_with_circuit_interface'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-operation-0.10.1/lib/trailblazer/operation/public_call.rb:17:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/call_task.rb:13:in `call_task'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `block in call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `each'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit.rb:45:in `block in call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit.rb:44:in `loop'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/circuit.rb:44:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity.rb:13:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-dsl-linear-1.2.4/lib/trailblazer/activity/dsl/linear/strategy.rb:105:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-operation-0.10.1/lib/trailblazer/operation/public_call.rb:61:in `call_with_circuit_interface'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-operation-0.10.1/lib/trailblazer/operation/public_call.rb:94:in `call_task'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `block in call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `each'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-activity-0.16.1/lib/trailblazer/activity/task_wrap.rb:28:in `invoke'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-operation-0.10.1/lib/trailblazer/operation/public_call.rb:40:in `call_with_public_interface'
     # ./.bundle/ruby/3.2.0/gems/trailblazer-operation-0.10.1/lib/trailblazer/operation/public_call.rb:19:in `call'
     # ./spec/concepts/polymorphic/sms_campaigns/operation/create_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/concepts/polymorphic/sms_campaigns/operation/create_spec.rb:40:in `block (5 levels) in <top (required)>'
     # ./.bundle/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./.bundle/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./.bundle/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./.bundle/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./.bundle/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
```

**Comment by n-rodriguez** [comment]
> The file was added intentionally as the default for tests

that might the issue : your defaults are not the one I expect in my application. Resetting/redefining Flipper policies for each test is a bit... unexpected.

**Comment by bkeepers** [comment]
@n-rodriguez You an disable it with:

```ruby
Rails.application.configure do
  config.flipper.test_help = false
end
```

**Comment by n-rodriguez** [comment]
@bkeepers thank you! 

Note: an opt-in settings would have been better IMHO

**Comment by jnunemaker** [comment]
@n-rodriguez I can see how you would feel that and I'm bummed it was a pain to hunt down for you. 

In this instance, opt-in is less ideal to the entire flipper audience though. Most people want a fast in memory adapter that clears before each test. Before they had to add code to make it work this way. Now it works that way by default, which is better for the majority.

**Comment by n-rodriguez** [comment]
@jnunemaker thanks for the clarification!
