### ISSUE TITLE
ActiveRecord adapter: unexpected error when running in a transaction

### ISSUE THREAD

**Issue by tjefferson08** [flippercloud/flipper#866]
Calling `enable_actor` is not idempotent (from the application perspective)

1st time: 😄 
2nd time: 😡 

```ruby
test "enable_actor is not idempotent" do
  actor = create(:actor)

  run_enable_in_transaction = -> {
    ActiveRecord::Base.transaction do
      Flipper.enable_actor(:foo, actor)
    end
  }

  assert_nothing_raised { run_enable_in_transaction.call }

  assert_raises(ActiveRecord::StatementInvalid) { run_enable_in_transaction.call }
end
```

The observed effect:
Running flipper code in a transaction can unexpectedly "poison" the transaction

As I understand it, this is because the AR adapter is relying solely on DB constraints to enforce uniqueness, whereas most rails apps combine DB constraints for uniqueness with a corresponding validation on the AR model

**Comment by jnunemaker** [comment]
Hi! Can you paste the full statement invalid error? We rescue `ActiveRecord::RecordNotUnique` ([source](https://github.com/flippercloud/flipper/blob/main/lib/flipper/adapters/active_record.rb#L256)), but maybe some other database is raising a statement invalid with a lower level unique error for some reason. 

What version of rails are you using and what database?

**Comment by tjefferson08** [comment]
full error message:

`PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block`

which makes sense to me, the INSERT statement from flipper fails, which aborts the transaction

I'm using rails `7.1.3.1` and Postgres version `14.11` but I suspect it may be reproducible on other databases/versions.

**Comment by jnunemaker** [comment]
@tjefferson08 can you get the failure from flipper? Add a rescue around it and puts the error or something? I want to see what error is failing the transaction, because as I said above, we have a rescue for this so its idempotent, so it must be something different that is being raised that we aren't rescuing. Thanks!

**Comment by tjefferson08** [comment]
>something different that is being raised that we aren't rescuing

I think the "something different" is the `ActiveRecord::StatementInvalid`

I would not expect rescuing `ActiveRecord::RecordNotUnique` to _also_ rescue `ActiveRecord::StatementInvalid`

I tried to get a failing test into the flipper test suite but I couldn't get any of the adapter-specific tests to run (even after following the docker-compose instructions)

**Comment by jnunemaker** [comment]
Where was the original test case from in the issue above? The problem is we can’t replicate it so that’s why I need you to so that I can see what is inside of the active record statement invalid because I don’t want to rescue all of those as that would lead to problems, I’ll likely have to check the error message in addition to the class.

**Comment by tjefferson08** [comment]
yeah rescuing `StatementInvalid` sounds like a bad idea for sure, lotta stuff could hide in there

the test from the report was something I cooked up within my rails app's test suite as I was troubleshooting this error (it was causing an issue in one of our controllers)

I'm still trying to get the flipper test suite to go locally, I made some progress by updating some of the docker configs

a minimal new rails app might be another avenue for reproducing

**Comment by jnunemaker** [comment]
@tjefferson08 could you just run it from your app again? If I can just see what the error is I can setup a test to fix it. Maybe this?

```ruby
ActiveRecord::Base.transaction do
  begin
    Flipper.enable_actor(:foo, actor)
  rescue => e
    p e
    raise
  end
end
```

**Comment by tjefferson08** [comment]
Here's the trace I get from minitest:

```09:28 $  bundle exec ruby -Ilib\:test\:spec test/models/ops_account_test.rb -n/enable_actor_is_not_idempotent/ -bv
Running 4 tests in a single process (parallelization threshold is 50)

# Running tests with run options -n/enable_actor_is_not_idempotent/ -bv --seed 21648:


OpsAccountTest#test_enable_actor_is_not_idempotent 0.44 = E

Finished tests in 0.440565s, 2.2698 tests/s, 0.0000 assertions/s.


Error:
OpsAccountTest#test_enable_actor_is_not_idempotent:
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `block (2 levels) in raw_execute'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `block in raw_execute'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:53:in `raw_execute'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:521:in `internal_execute'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/savepoints.rb:20:in `release_savepoint'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:359:in `commit'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:514:in `block in commit_transaction'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:503:in `commit_transaction'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:565:in `block in within_new_transaction'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
    /Users/travis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.1/lib/active_record/transactions.rb:212:in `transaction'
    test/models/ops_account_test.rb:26:in `block in <class:OpsAccountTest>'

1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

I was also able to get a failure to show up within the flipper test suite:

```ruby 
# spec/lib/adapters/active_record_spec.rb, added at line 66
it 'should not poision wrapping transactions' do
  flipper = Flipper.new(subject)

  actor = Struct.new(:flipper_id).new('flipper-id-123')
  flipper.enable_actor(:foo, actor)

  ActiveRecord::Base.transaction do
    2.times { flipper.enable_actor(:foo, actor) }
  end
end
```

I don't know why I have to run it 2 times within the transaction here 🤷

**Comment by tjefferson08** [comment]
ah OK I narrowed this down

it's not until the "next read" that the transaction explodes

```ruby
it 'should not poision wrapping transactions' do
  flipper = Flipper.new(subject)

  actor = Struct.new(:flipper_id).new('flipper-id-123')
  flipper.enable_actor(:foo, actor)

  ActiveRecord::Base.transaction do
    flipper.enable_actor(:foo, actor)

    # we get here just fine!
    puts 'got here!'
    expect(true).to be true

    # whoa it's not until the next read that the transaction blows up
    # with StatementInvalid
    expect(Flipper::Adapters::ActiveRecord::Gate.count).to eq 1
    puts 'never got here!'
    expect(true).to be false
  end
end
```

**Comment by tjefferson08** [comment]
the original test I provided was part of our rails app's test suite, so yes, that uses transactions to keep tests from polluting one another (rails default behavior)

but I ran that last [code snippet](https://github.com/flippercloud/flipper/issues/866#issuecomment-2110300328)  within flipper's own test suite; hopefully you can reproduce that

**Comment by tjefferson08** [comment]
@jnunemaker here's [a PR](https://github.com/flippercloud/flipper/pull/867) with that test failing, just to be super clear

sorry, I know PR comments can sometimes be kinda indecipherable

**Comment by jnunemaker** [comment]
@tjefferson08 Thanks! I'll take a look. Sorry this hit right during a busy stretch and then vacation. I'll see what I can get figured out.

**Comment by nhorton** [comment]
We are seeing flavors of this too. My initial question was whether there was a way to get flipper to use nested transactions or a fully-separate DB connection to prevent this.

**Comment by nhorton** [comment]
Any updates on this? We are starting to remove flipper from some key code paths because we are hitting this so much in production right now.

**Comment by jnunemaker** [comment]
https://github.com/flippercloud/flipper/pull/881 has this fixed. Should have a new release soon. I think there are a couple small things I want to sneak in before next release.

**Comment by tjefferson08** [comment]
thanks @jnunemaker 🥇
